let games = {
    games: [
        {
            gameid: "wordfight",
            supportedLocales : ["el_GR"],
            bgImage: "/promoassets/wordfight/icon.png",
            icon: "/promoassets/wordfight/bg.png",
            orientation: "portrait",
            publisherLogo : "/promoassets/abstact/bt_logo.png",
            terms: "http://bug.town/terms.html",
            policy: "https://bug.town/privacy-policy.html",
            fb_namespace: "bt_wordfight",
            gameUrl: ""
        },
        {
            gameid: "yatzy",
            supportedLocales : ["el_GR", "en_US"],
            bgImage: "/promoassets/yatzy/promoIcon.png",
            icon: "/promoassets/yatzy/bg.png",
            orientation: "portrait",
            publisherLogo : "/promoassets/abstact/ll_logo.png",
            terms: "http://lazyland.net/legal/termsofservice.htm?locale=en_US",
            policy: "http://lazyland.net/legal/privacypolicy.html?locale=en_US",
            fb_namespace: "ll_yatzy",
            gameUrl: ""
        },
        {
            gameid: "kseri",
            supportedLocales : ["el_GR"],
            bgImage: "/promoassets/kseri/promoIcon.png",
            icon: "/promoassets/kseri/bg.png",
            orientation: "portrait",
            publisherLogo : "/promoassets/abstact/ll_logo.png",
            terms: "http://lazyland.net/legal/termsofservice.htm?locale=en_US",
            policy: "http://lazyland.net/legal/privacypolicy.html?locale=en_US",
            fb_namespace: "ll_kseri",
            gameUrl: ""
        },
        {
            gameid: "agonia",
            supportedLocales : ["el_GR"],
            bgImage: "/promoassets/agonia/promoIcon.png",
            icon: "/promoassets/agonia/bg.png",
            orientation: "portrait",
            publisherLogo : "/promoassets/abstact/ll_logo.png",
            terms: "http://lazyland.net/legal/termsofservice.htm?locale=en_US",
            policy: "http://lazyland.net/legal/privacypolicy.html?locale=en_US",
            fb_namespace: "ll_agonia",
            gameUrl: ""
        },
        {
            gameid: "backgammon",
            supportedLocales : ["el_GR"],
            bgImage: "/promoassets/backgammon/promoIcon.png",
            icon: "/promoassets/backgammon/bg.png",
            orientation: "landscape",
            publisherLogo : "/promoassets/abstact/ll_logo.png",
            terms: "http://lazyland.net/legal/termsofservice.htm?locale=en_US",
            policy: "http://lazyland.net/legal/privacypolicy.html?locale=en_US",
            fb_namespace: "ll_backgammon",
            gameUrl: ""
        },
        {
            gameid: "mahjong",
            supportedLocales : ["el_GR", "en_US"],
            bgImage: "/promoassets/mahjong/promoIcon.png",
            icon: "/promoassets/mahjong/bg.png",
            orientation: "landscape",
            publisherLogo : "/promoassets/abstact/ll_logo.png",
            terms: "http://lazyland.net/legal/termsofservice.htm?locale=en_US",
            policy: "http://lazyland.net/legal/privacypolicy.html?locale=en_US",
            fb_namespace: "ll_mahjong",
            gameUrl: ""
        },
        {
            gameid: "backgammonus",
            supportedLocales : ["en_US"],
            bgImage: "/promoassets/backgammonus/promoIcon.png",
            icon: "/promoassets/backgammonus/bg.png",
            orientation: "landscape",
            publisherLogo : "/promoassets/abstact/ll_logo.png",
            terms: "http://lazyland.net/legal/termsofservice.htm?locale=en_US",
            policy: "http://lazyland.net/legal/privacypolicy.html?locale=en_US",
            fb_namespace: "ll_backgammonus",
            gameUrl: ""
        },
        {
            gameid: "blackjack",
            supportedLocales : ["el_GR","en_US"],
            bgImage: "/promoassets/blackjack/promoIcon.png",
            icon: "/promoassets/blackjack/bg.png",
            orientation: "landscape",
            publisherLogo : "/promoassets/abstact/ll_logo.png",
            terms: "http://lazyland.net/legal/termsofservice.htm?locale=en_US",
            policy: "http://lazyland.net/legal/privacypolicy.html?locale=en_US",
            fb_namespace: "ll_blackjack",
            gameUrl: ""
        },
        {
            gameid: "candy",
            supportedLocales : ["el_GR","en_US"],
            bgImage: "/promoassets/candy/promoIcon.png",
            icon: "/promoassets/candy/bg.png",
            orientation: "landscape",
            publisherLogo : "/promoassets/abstact/ll_logo.png",
            terms: "http://lazyland.net/legal/termsofservice.htm?locale=en_US",
            policy: "http://lazyland.net/legal/privacypolicy.html?locale=en_US",
            fb_namespace: "ll_candy",
            gameUrl: ""
        },
        {
            gameid: "farkle",
            supportedLocales : ["el_GR","en_US"],
            bgImage: "/promoassets/farkle/promoIcon.png",
            icon: "/promoassets/farkle/bg.png",
            orientation: "landscape",
            publisherLogo : "/promoassets/abstact/ll_logo.png",
            terms: "http://lazyland.net/legal/termsofservice.htm?locale=en_US",
            policy: "http://lazyland.net/legal/privacypolicy.html?locale=en_US",
            fb_namespace: "ll_farkle",
            gameUrl: ""
        },
        {
            gameid: "klondike",
            supportedLocales : ["el_GR","en_US"],
            bgImage: "/promoassets/klondike/promoIcon.png",
            icon: "/promoassets/klondike/bg.png",
            orientation: "landscape",
            publisherLogo : "/promoassets/abstact/ll_logo.png",
            terms: "http://lazyland.net/legal/termsofservice.htm?locale=en_US",
            policy: "http://lazyland.net/legal/privacypolicy.html?locale=en_US",
            fb_namespace: "ll_klondike",
            gameUrl: ""
        },
        {
            gameid: "pool",
            supportedLocales : ["el_GR","en_US"],
            bgImage: "/promoassets/pool/promoIcon.png",
            icon: "/promoassets/pool/bg.png",
            orientation: "landscape",
            publisherLogo : "/promoassets/abstact/ll_logo.png",
            terms: "http://lazyland.net/legal/termsofservice.htm?locale=en_US",
            policy: "http://lazyland.net/legal/privacypolicy.html?locale=en_US",
            fb_namespace: "ll_pool",
            gameUrl: ""
        },
        {
            gameid: "roulette",
            supportedLocales : ["el_GR","en_US"],
            bgImage: "/promoassets/roulette/promoIcon.png",
            icon: "/promoassets/roulette/bg.png",
            orientation: "landscape",
            publisherLogo : "/promoassets/abstact/ll_logo.png",
            terms: "http://lazyland.net/legal/termsofservice.htm?locale=en_US",
            policy: "http://lazyland.net/legal/privacypolicy.html?locale=en_US",
            fb_namespace: "ll_roulette",
            gameUrl: ""
        },
        {
            gameid: "scratch",
            supportedLocales : ["el_GR","en_US"],
            bgImage: "/promoassets/scratch/promoIcon.png",
            icon: "/promoassets/scratch/bg.png",
            orientation: "landscape",
            publisherLogo : "/promoassets/abstact/ll_logo.png",
            terms: "http://lazyland.net/legal/termsofservice.htm?locale=en_US",
            policy: "http://lazyland.net/legal/privacypolicy.html?locale=en_US",
            fb_namespace: "ll_scratch",
            gameUrl: ""
        },
        {
            gameid: "solitaire",
            supportedLocales : ["el_GR","en_US"],
            bgImage: "/promoassets/solitaire/promoIcon.png",
            icon: "/promoassets/solitaire/bg.png",
            orientation: "landscape",
            publisherLogo : "/promoassets/abstact/ll_logo.png",
            terms: "http://lazyland.net/legal/termsofservice.htm?locale=en_US",
            policy: "http://lazyland.net/legal/privacypolicy.html?locale=en_US",
            fb_namespace: "ll_solitaire",
            gameUrl: ""
        },


    ],
    activeGame: "wordfight"
}